version: '3.4'

networks:
  main-network:
services:
  frontend-service:
    build:
      context: my-app
      dockerfile: Dockerfile
      args:
        - API_DOMAIN=localhost:5124
    networks:
      - main-network
    ports:
      - 81:3000
volumes:
  proxy:
  node_modules:
