version: '3.4'

networks:
  main-network:
services:
  frontend-service:
    build:
      context: AngularService
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:5124
        - API_DOMAIN=localhost:5124
    networks:
      - main-network
    ports:
      - 80:4200
      - 443:443
volumes:
  proxy:
  node_modules:
